---
- hosts: all
  connection: local
  gather_facts: false
  vars:
    # override on command line if needed
    target_hostname: "{{ inventory_hostname }}"
    target_username: "{{ username | default('admin') }}"
    target_password: "{{ password }}"
    platform_type: "{{ device_type | default('ucs') }}"
    target_proxy_host: "{{ proxy_host | default('') }}"
    target_proxy_port: "{{ proxy_port | default(0) }}"
    target_read_only: "{{ read_only | default(false) }}"
    target_resource_groups: "{{ resource_groups | default(omit) }}"
  environment:
    PYTHONPATH: "{{ playbook_dir }}"
  tasks:
    - name: Define JSON string passed to claim script
      set_fact:
        # JSON for each host being claimed.
        # Quotes and whitespace are importantant for the JSON string passed to claim script.
        # ----------
        stash_json: ' { "hostname": "{{ target_hostname }}",
          "username": "{{ target_username }}",
          "password": "{{ target_password }}",
          "device_type": "{{ platform_type }}",
          "proxy_host": "{{ target_proxy_host }}",
          "proxy_port": "{{ target_proxy_port }}",
          "read_only": "{{ target_read_only }}",
          "resource_groups": ["{{ target_resource_groups }}"]
          }'
    - name: Claim targets
      script: /usr/bin/env python claim_target.py -t ' [{{ stash_json }}]'
      register: result
      changed_when: '"true" in result.stdout'
